Page({
    data:{
       weather:{
           wendu:18,
           gaomao:'昼夜温差比较大，容易感冒，请适当添加衣服。体质较弱的朋友请注意防护。',
           yesterday:{
               date:'17日星期四',
               type:'阴',
               dx:'南风',
               fx:'微风级',
               low:'低温8℃',
               high:'高温18℃'
           },
           forecast:[
               {
                   date:'18日星期五',
                   type:'晴朗',
                   dx:'南风',
                   fx:'微风级',
                   low:'低温8℃',
                   high:'高温18℃'
               },
               {
                   date:'18日星期五',
                   type:'晴朗',
                   dx:'南风',
                   fx:'微风级',
                   low:'低温8℃',
                   high:'高温18℃'
               },
               {
                   date:'18日星期五',
                   type:'晴朗',
                   dx:'南风',
                   fx:'微风级',
                   low:'低温8℃',
                   high:'高温18℃'
               },
               {
                   date:'18日星期五',
                   type:'晴朗',
                   dx:'南风',
                   fx:'微风级',
                   low:'低温8℃',
                   high:'高温18℃'
               },
               {
                   date:'18日星期五',
                   type:'晴朗',
                   dx:'南风',
                   fx:'微风级',
                   low:'低温8℃',
                   high:'高温18℃'
               }

           ]
       },
        today:'2018-03-27',
        city:'北京',
        inputCity:''
    }
})